apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agro-cd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://git-codecommit.ap-south-1.amazonaws.com/v1/repos/k8s
    targetRevision: HEAD
    path: development
  destination:
    server: https://kubernetes.default.svc
    namespace: development
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    
    automated:
      selfHeal: true
      prune: true