apiVersion: v1
kind: Secret
metadata:
  name: private-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://git-codecommit.ap-south-1.amazonaws.com/v1/repos/k8s
  username: <UserName>
  password: <Password>
  
